create extension if not exists pgcrypto;

create table if not exists public.partner_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  phone text,
  region text,
  role text not null default 'referenciador'
    check (role in ('referenciador', 'consultor', 'leader', 'admin')),
  personal_slug text not null unique,
  leader_id uuid references public.partner_profiles(user_id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.partner_profiles
  drop constraint if exists partner_profiles_role_check;

alter table public.partner_profiles
  add constraint partner_profiles_role_check
  check (role in ('referenciador', 'consultor', 'leader', 'admin'));

create table if not exists public.partner_references (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  client_name text not null,
  client_phone text not null,
  postal_code text not null,
  product text not null check (product in ('Telecom', 'Energia', 'Ambos')),
  status text not null default 'Recebida'
    check (status in ('Recebida', 'Em contacto', 'Proposta', 'Venda', 'Em validação', 'Venda validada', 'Comissão disponível')),
  source text not null default 'Formulário manual',
  consent_given boolean not null check (consent_given = true),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists partner_references_user_created_idx
  on public.partner_references (user_id, created_at desc);

create index if not exists partner_profiles_leader_idx
  on public.partner_profiles (leader_id);

alter table public.partner_profiles enable row level security;
alter table public.partner_references enable row level security;

revoke all on table public.partner_profiles from anon, authenticated;
revoke all on table public.partner_references from anon, authenticated;
grant select on table public.partner_profiles to authenticated;
grant select, insert on table public.partner_references to authenticated;
grant usage, select on sequence public.partner_references_id_seq to authenticated;

drop policy if exists "Partners read their account and assigned team" on public.partner_profiles;
create policy "Partners read their account and assigned team"
  on public.partner_profiles for select
  to authenticated
  using (
    (select auth.uid()) = user_id
    or (select auth.uid()) = leader_id
  );

drop policy if exists "Partners read their references" on public.partner_references;
create policy "Partners read their references"
  on public.partner_references for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "Partners create their references" on public.partner_references;
create policy "Partners create their references"
  on public.partner_references for insert
  to authenticated
  with check ((select auth.uid()) = user_id and consent_given = true);

create or replace function public.handle_new_partner()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.partner_profiles (user_id, full_name, personal_slug)
  values (
    new.id,
    coalesce(nullif(new.raw_user_meta_data ->> 'full_name', ''), split_part(new.email, '@', 1)),
    'parceiro-' || substr(replace(new.id::text, '-', ''), 1, 10)
  )
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_partner();

insert into public.partner_profiles (user_id, full_name, personal_slug)
select
  users.id,
  coalesce(nullif(users.raw_user_meta_data ->> 'full_name', ''), split_part(users.email, '@', 1)),
  'parceiro-' || substr(replace(users.id::text, '-', ''), 1, 10)
from auth.users
where not exists (
  select 1 from public.partner_profiles profiles where profiles.user_id = users.id
);

create or replace function public.get_my_team_summary()
returns table (
  user_id uuid,
  full_name text,
  role text,
  sales bigint,
  pipeline bigint,
  conversion integer,
  last_sale date
)
language sql
security definer
set search_path = ''
stable
as $$
  select
    member.user_id,
    member.full_name,
    member.role,
    count(reference.id) filter (where reference.status in ('Venda validada', 'Comissão disponível')) as sales,
    count(reference.id) filter (where reference.status not in ('Venda validada', 'Comissão disponível')) as pipeline,
    case
      when count(reference.id) = 0 then 0
      else round(
        100.0 * count(reference.id) filter (where reference.status in ('Venda validada', 'Comissão disponível'))
        / count(reference.id)
      )::integer
    end as conversion,
    (max(reference.created_at) filter (where reference.status in ('Venda validada', 'Comissão disponível')))::date as last_sale
  from public.partner_profiles member
  left join public.partner_references reference on reference.user_id = member.user_id
  where member.leader_id = (select auth.uid())
    and exists (
      select 1
      from public.partner_profiles current_partner
      where current_partner.user_id = (select auth.uid())
        and current_partner.role = 'leader'
    )
  group by member.user_id, member.full_name, member.role
  order by sales desc, member.full_name;
$$;

revoke all on function public.get_my_team_summary() from public;
grant execute on function public.get_my_team_summary() to authenticated;

create or replace function public.get_admin_partners_summary()
returns table (
  user_id uuid,
  full_name text,
  email text,
  phone text,
  region text,
  role text,
  leader_id uuid,
  leader_name text,
  total_references bigint,
  validated_sales bigint,
  pipeline bigint,
  conversion integer,
  estimated_commission numeric,
  created_at timestamptz,
  last_activity date
)
language sql
security definer
set search_path = ''
stable
as $$
  select
    profile.user_id,
    profile.full_name,
    user_account.email::text,
    profile.phone,
    profile.region,
    profile.role,
    profile.leader_id,
    leader.full_name as leader_name,
    count(reference.id) as total_references,
    count(reference.id) filter (where reference.status in ('Venda validada', 'Comissão disponível')) as validated_sales,
    count(reference.id) filter (where reference.status not in ('Venda validada', 'Comissão disponível')) as pipeline,
    case
      when count(reference.id) = 0 then 0
      else round(
        100.0 * count(reference.id) filter (where reference.status in ('Venda validada', 'Comissão disponível'))
        / count(reference.id)
      )::integer
    end as conversion,
    coalesce(sum(
      case
        when reference.status not in ('Venda validada', 'Comissão disponível') then 0
        when profile.role = 'referenciador' then 10
        when profile.role in ('consultor', 'leader') then 25
        else 0
      end
    ), 0)::numeric as estimated_commission,
    profile.created_at,
    (max(reference.created_at))::date as last_activity
  from public.partner_profiles profile
  join auth.users user_account on user_account.id = profile.user_id
  left join public.partner_profiles leader on leader.user_id = profile.leader_id
  left join public.partner_references reference on reference.user_id = profile.user_id
  where exists (
    select 1
    from public.partner_profiles administrator
    where administrator.user_id = (select auth.uid())
      and administrator.role = 'admin'
  )
  group by
    profile.user_id,
    profile.full_name,
    user_account.email,
    profile.phone,
    profile.region,
    profile.role,
    profile.leader_id,
    leader.full_name,
    profile.created_at
  order by validated_sales desc, profile.full_name;
$$;

create or replace function public.get_admin_references()
returns table (
  reference_id bigint,
  user_id uuid,
  owner_name text,
  owner_email text,
  owner_role text,
  owner_leader_id uuid,
  client_name text,
  client_phone text,
  postal_code text,
  product text,
  status text,
  source text,
  notes text,
  created_at timestamptz
)
language sql
security definer
set search_path = ''
stable
as $$
  select
    reference.id,
    reference.user_id,
    profile.full_name,
    user_account.email::text,
    profile.role,
    profile.leader_id,
    reference.client_name,
    reference.client_phone,
    reference.postal_code,
    reference.product,
    reference.status,
    reference.source,
    reference.notes,
    reference.created_at
  from public.partner_references reference
  join public.partner_profiles profile on profile.user_id = reference.user_id
  join auth.users user_account on user_account.id = reference.user_id
  where exists (
    select 1
    from public.partner_profiles administrator
    where administrator.user_id = (select auth.uid())
      and administrator.role = 'admin'
  )
  order by reference.created_at desc;
$$;

revoke all on function public.get_admin_partners_summary() from public;
revoke all on function public.get_admin_references() from public;
grant execute on function public.get_admin_partners_summary() to authenticated;
grant execute on function public.get_admin_references() to authenticated;
